"""Add valor_desconto to item_despesa

Revision ID: 73d7225ddc86
Revises: 9972d28b97c3
Create Date: 2026-07-09 09:44:40.874802

"""

from __future__ import annotations

from collections.abc import Sequence  # noqa: TC003

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d7225ddc86"
down_revision: str | Sequence[str] | None = "9972d28b97c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itens_despesa",
        sa.Column(
            "valor_desconto", sa.Numeric(precision=13, scale=2), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("itens_despesa", "valor_desconto")
    # ### end Alembic commands ###
